# Test this package
#
# Currently we need to use the nightly snapshots, because we need a
# special testing-only API from the Concurrency runtime.

name: Test Windows

on:
  push:
    branches: [ "main", "add-test-action" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-windows:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Swift nightly
        working-directory: ./scripts
        run: |
          ./install-nightly.ps1

          # Reset path
          echo ($env:Path).Replace(';',"`n") `
            | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

          # Add SDKROOT to the environment
          Add-Content $env:GITHUB_ENV "SDKROOT=$env:SDKROOT"

      - name: Build
        run: |
          swift build

      - name: Test
        run: |
          swift test
